### ISSUE TITLE
Improvements to benchmarks

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly-lz4#11]
1. There are too many benchmarks, its difficult to analyze because of the noise. We should keep only those which provide us some useful information:
a. remove the compress.decompress benchmarks. Usual use case is to either compress a stream or decompress a stream, it should be enough to measure these two separately.
b. We can use 1 decompressResized benchmark for comparison how much difference resizing makes, we do not need all benchmarks to have these variants. Most of the time we would be resizing anyway.
c. We can run 1 benchmark with multiple acceleration values to compare how much difference acceleration makes. We should not run all benchmark variants with all acceleration values.
2. 64K block size would probably be optimal because the dictionary is maximum 64K. We can use a small block size (64 bytes), 64K, and a big block size (1 MB) for comparisons. We do not need to run all benchmarks with all buffer sizes. We can run one benchmark with all buffer sizes not all of them.
3. Make all the input files of equal size so that we can compare the benchmarks. We can replicate the data to make them all 5MB or 10MB.
4. Add a way to benchmark external files, like we have in streamly FileSystem.Handle benchmarks.

**Comment by adithyaov** [comment]
> remove the compress.decompress benchmarks. Usual use case is to either compress a stream or decompress a stream, it should be enough to measure these two separately.

We can only decompress a compressed stream so a standalone decompress is not possible unless we use a compressed file as input.
> Make all the input files of equal size so that we can compare the benchmarks. We can replicate the data to make them all 5MB or 10MB.

The best way to this, I feel is using a simple script after downloading the corpora.

**Comment by harendra-kumar** [comment]
Yes, we should compress and use the compressed file. Basically we want to just leave out the compress from the benchmark measurement.

**Comment by adithyaov** [comment]
See #18 and #23
