### ISSUE TITLE
Proposed compress and decompress APIs

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly-lz4#13]
Compress:
* `compress`: A convenience API that uses a default speedup factor and a default block size for compression
* `compressWith`: ability to specify speedup and block size
* `compressRaw`: compress the arrays in the input stream as is without resizing

Decompress:
* `decompress`:  resize the input arrays and decompress
* `decompressRaw`: assume the arrays are of the right size already

**Comment by adithyaov** [comment]
Taking #16 into account, should the APIs be `compressChunks`, `compressChunksWith`, etc.?
